# Shared configuration constants for the localization pipeline.
from __future__ import annotations

from typing import Any, Dict

OUTPUT_POSE_SPEC = "colmap_world_quat_t"

REQUIRED_USER_INPUT: Dict[str, Any] = {
    "Q1_topk": 20,
    "Q2_vggt_checkpoint_path": "",  # optional: local path; empty=auto local discovery
    "Q6_align_transform_type": "Sim3",  # REQUIRED: "Sim3" or "SE3"
    "Q8_visualization_spec": {
        "frustum_near": 0.02,
        "frustum_far": 0.12,
    },
}

RETRIEVAL_METHOD = "megaloc"

ALIGN_RANSAC_ITERS = 2000
ALIGN_INLIER_THRESH_M = 0.30
ALIGN_MIN_INLIERS = 5
ALIGN_FALLBACK_RANSAC_ITERS = 6000
ALIGN_FALLBACK_INLIER_THRESH_M = 0.40
ALIGN_FALLBACK_MIN_INLIERS = 4
ALIGN_SEED = 42

# Ref selection (retrieval top-20 -> query + up to 8 refs for final VGGT call)
REF_SELECTION_MAX_CANDIDATES = 20
REF_SELECTION_ANCHORS = 3
REF_SELECTION_POOL_SIZE = 10
REF_SELECTION_FINAL_COUNT = 8
REF_SELECTION_SIM_TAU = 0.02
REF_SELECTION_MIN_POINTS3D = 50
REF_SELECTION_GREEDY_CONSISTENCY_WEIGHT = 2.0
REF_SELECTION_GREEDY_DIVERSITY_WEIGHT = 0.75
REF_SELECTION_GREEDY_RETRIEVAL_WEIGHT = 0.25
REF_SELECTION_BASELINE_Q_LOW = 0.25
REF_SELECTION_BASELINE_Q_HIGH = 0.75
REF_SELECTION_SOFT_SIM_FLOOR = 0.01
# objective defaults
REF_SELECTION_DOPT_LAMBDA_PRIOR = 1.0e-5
REF_SELECTION_DOPT_BETA_STRUCT = 0.5

# Same-space validation from VGGT tracks
VGGT_TRACK_QUERY_GRID_COLS = 16
VGGT_TRACK_QUERY_GRID_ROWS = 16
SAME_SPACE_TRACK_VIS_THRESH = 0.20
SAME_SPACE_TRACK_CONF_THRESH = 0.10
SAME_SPACE_REF_CONNECTED_EDGE_THRESH = 0.01
SAME_SPACE_MIN_TOTAL_TRACKS = 32
SAME_SPACE_MIN_QUERY_TRACK_PARTICIPATION_RATIO = 0.20
SAME_SPACE_MIN_QUERY_TRACKS_WITH_2PLUS_REFS = 20
SAME_SPACE_MIN_QUERY_TRACKS_WITH_2PLUS_REFS_RATIO = 0.10
SAME_SPACE_MIN_QUERY_TRACKS_WITH_2PLUS_REFS_FLOOR = 10
SAME_SPACE_MIN_REFS_CONNECTED_TO_QUERY = 2
SAME_SPACE_MIN_QUERY_REF_MEAN_EDGE_WEIGHT = 0.01
SAME_SPACE_MIN_QUERY_REF_GAP_RATIO = 0.15
SAME_SPACE_WEAK_MAX_FAILED_RULES = 1
SAME_SPACE_ALLOW_WEAK_PASS = False
SAME_SPACE_QUERY_TRACK_TOPK = 128
SAME_SPACE_QUERY_TRACK_MIN_SCORE = 0.0
SAME_SPACE_PRUNING_MIN_REF_OBS = 1
SAME_SPACE_PRUNING_REF_AWARE_BLEND = 0.5
SAME_SPACE_PRUNING_REF_AWARE_BASE = 0.25

# Query image preprocessing (applied before retrieval + VGGT)
QUERY_ORIENTATION_DEFAULT = "Original"
QUERY_ORIENTATION_VALUES = (
    "Original",
    "Portrait",
    "LandscapeLeft",
    "LandscapeRight",
    "PortraitUpsideDown",
)
QUERY_PREPROCESS_FORCE_RESIZE = False
QUERY_PREPROCESS_TARGET_SIZE_LANDSCAPE = (1280, 720)  # (width, height)
QUERY_PREPROCESS_TARGET_SIZE_PORTRAIT = (720, 1280)  # (width, height)
QUERY_PREPROCESS_IMAGE_FORMAT = "JPEG"
QUERY_PREPROCESS_JPEG_QUALITY = 95

# Visualization exports (PLY)
REFINE_ENABLE_DEFAULT = True
REFINE_PNP_ENABLE_DEFAULT = True
REFINE_BA_ENABLE_DEFAULT = True
DEPTH_REFINEMENT_ENABLE_DEFAULT = True
REFINE_MIN_CORRESPONDENCES_DEFAULT = 20
REFINE_PNP_REPROJ_ERROR_PX = 8.0
REFINE_PNP_MIN_INLIER_RATIO = 0.25
REFINE_PNP_MAX_REPROJ_MEAN_PX = 8.0
REFINE_BA_MAX_RMSE_PX = 8.0
REFINE_BA_MIN_INLIERS = 30
REFINE_WEIGHTED_REFINEMENT_ENABLE_DEFAULT = True
REFINE_WEIGHTED_MIN_PIXEL_SIGMA_PX = 1.0
REFINE_WEIGHTED_BASE_IMAGE_SIGMA_PX = 2.0
REFINE_WEIGHTED_ASSOC_SIGMA_SCALE = 0.5
REFINE_WEIGHTED_HUBER_DELTA = 2.5
REFINE_WEIGHTED_MAX_ITERS = 10
# minimum Gauss-Newton iterations before early-exit
REFINE_WEIGHTED_MIN_ITERS = 3
# Final pose fusion modes.
FUSION_MODES = (
    "align_only",
    "refined_only",
    "always_refined",
    "fixed_alpha",
    "hard_gated_refined",
    "uncertainty_fusion_no_gate",
    "gated_uncertainty_fusion",
    "gated_uncertainty_fusion_decoupled",
    "uncertainty_alpha_decoupled",
    "rotation_salvage",
)
# numerical floor for precision computations
FUSION_ALPHA_PRECISION_EPS = 1.0e-12
FUSION_MODE_DEFAULT = "gated_uncertainty_fusion"
FUSION_FIXED_ALPHA = 0.30
FUSION_COVARIANCE_DAMPING = 1.0e-6
FUSION_MIN_REFINED_RELIABILITY = 1.0e-3
FUSION_CONSISTENCY_GATE_ENABLED = True
FUSION_CHI2_THRESHOLD_SE3 = 12.59
FUSION_CHI2_THRESHOLD_TRANSLATION = 7.81
FUSION_ACTION_ON_FAIL = "align"
FUSION_DEFAULT_ALIGN_RELIABILITY = 1.0
FUSION_DEFAULT_REFINED_RELIABILITY = 1.0
REFINE_BA_CENTER_PRIOR_ENABLE_DEFAULT = False
REFINE_BA_CENTER_PRIOR_SIGMA_M = 0.05

REFINE_FINAL_POSE_HYBRID_ALPHA = FUSION_FIXED_ALPHA
REFINE_FINAL_POSE_HYBRID_ENABLE = True
REFINE_CONSISTENCY_ENABLE_DEFAULT = True
REFINE_CONSISTENCY_MODE = "rollback_only"
REFINE_CONSISTENCY_CHI2_THRESHOLD_6D = 12.59
REFINE_CONSISTENCY_ETA_TRACE = 1.00
REFINE_CONSISTENCY_REQUIRE_BOTH_COVARIANCES = True
REFINE_CONSISTENCY_SKIP_ON_MISSING_COVARIANCE = True
REFINE_SPARSE_ANCHOR_ENABLE_DEFAULT = True
REFINE_SPARSE_ANCHOR_MAX_MATCH_DIST_PX = 14.0
REFINE_SPARSE_ANCHOR_MIN_REF_SUPPORT = 1
REFINE_SPARSE_ANCHOR_SCORE_RATIO = 1.5
REFINE_SPARSE_ANCHOR_ROUNDTRIP_MAX_MODEL_PX = 2.5
REFINE_SPARSE_ANCHOR_CONFLICT_RESCUE_WITH_DEPTH = False
REFINE_DEBUG_MAX_OBSERVATIONS_DUMP = 4096
REFINE_REPROJ_RESCUE_MULTIPLIER_DEFAULT = 4.0
REFINE_REPROJ_RESCUE_ALIGN_RMSE_RELAX_START = 0.08
REFINE_REPROJ_RESCUE_ALIGN_RMSE_WEAK = 0.15
REFINE_STABILITY_ENABLE_DEFAULT = True
REFINE_STABILITY_BOOTSTRAP_TRIALS = 12
REFINE_STABILITY_BOOTSTRAP_SAMPLE_RATIO = 0.7
REFINE_STABILITY_BOOTSTRAP_MIN_SUCCESS = 4
REFINE_STABILITY_ROT_P90_MAX_DEG = 12.0
REFINE_STABILITY_TRANS_P90_MAX_M = 1.5
REFINE_STABILITY_LOO_ROT_MAX_DEG = 15.0
REFINE_STABILITY_LOO_TRANS_MAX_M = 2.0
DEPTH_MAP_ROOT_ENV = "UNIFIED_COLMAP_DEPTH_ROOT"
DEPTH_MAX_REPROJ_ERROR_PX_DEFAULT = 24.0
DEPTH_MAX_CANDIDATE_SPREAD_M_DEFAULT = 1.5
DEPTH_MIN_SUPPORTING_REFS_DEFAULT = 1
DEPTH_MIN_VALID_CANDIDATES_DEFAULT = 1
DEPTH_SAMPLE_FALLBACK_RADIUS_PX = 3
DEPTH_SAMPLE_FALLBACK_MIN_SAMPLES = 2
